#!/bin/bash
# tModLoader server entrypoint wrapper.
# Generates serverconfig.txt from environment variables, detects existing worlds,
# performs hash-based mod installation, then execs the official management script.

set -euo pipefail

# Empty TMLVERSION trips up the manage script's get_version (it treats "" as a
# valid version string), making install-tml think the install is up to date
# even when it's broken. Treat empty == unset throughout.
if [[ -v TMLVERSION ]] && [[ -z "${TMLVERSION:-}" ]]; then
    unset TMLVERSION
fi

TML_FOLDER="${TML_FOLDER:-/tModLoader}"
MODS_DIR="${TML_FOLDER}/Mods"
WORLDS_DIR="${TML_FOLDER}/Worlds"
LOGS_DIR="${TML_FOLDER}/logs"
SERVERCONFIG="${TML_FOLDER}/serverconfig.txt"
MOD_HASH_FILE="${MODS_DIR}/.install-hash"
PRELOAD_DIR="${PRELOAD_DIR:-/preload}"

generate_serverconfig() {
    # Emit a serverconfig.txt body to stdout.
    # Arg 1: the world clause - either "world=<path>" or "autocreate=<size>".
    local world_clause="$1"

    cat <<EOF
# Auto-generated by entrypoint-wrapper.sh - edit .env on the host instead.
# Manual edits to this file will be overwritten on container restart.
worldpath=${WORLDS_DIR}
worldname=${WORLD_NAME}
${world_clause}
difficulty=${WORLD_DIFFICULTY}
maxplayers=${MAX_PLAYERS}
port=${SERVER_PORT}
password=${SERVER_PASSWORD}
motd=${MOTD}
secure=${SECURE}
language=${LANGUAGE}
autosave=${AUTOSAVE}
modpath=${MODS_DIR}
priority=1
EOF

    if [[ -n "${WORLD_SEED}" ]]; then
        echo "seed=${WORLD_SEED}"
    fi
}

determine_world_clause() {
    # Emit the world-related config lines.
    # Terraria's `autocreate` only works in conjunction with `-world`/`world=`,
    # which tells it where to create the file. Without `world=`, the server
    # ignores `autocreate` and drops into the interactive "Choose World:" prompt.
    # We always emit `world=<path>`, and add `autocreate=<size>` when the file
    # is missing so the server creates it at the same path.
    local target="${WORLDS_DIR}/${WORLD_NAME}.wld"
    echo "world=${target}"
    if [[ ! -f "$target" ]]; then
        echo "autocreate=${WORLD_SIZE}"
    fi
}

mods_need_install() {
    # Return 0 (success/true) if install.txt exists and differs from stored hash.
    # Return 1 (failure/false) if install.txt is missing or hash matches.
    local install_file="${MODS_DIR}/install.txt"
    [[ -f "$install_file" ]] || return 1

    local current_hash
    current_hash=$(sha256sum "$install_file" | awk '{print $1}')

    if [[ -f "$MOD_HASH_FILE" ]]; then
        local stored_hash
        stored_hash=$(cat "$MOD_HASH_FILE")
        [[ "$current_hash" != "$stored_hash" ]]
    else
        return 0
    fi
}

record_mod_hash() {
    # Write the current install.txt hash to MOD_HASH_FILE.
    local install_file="${MODS_DIR}/install.txt"
    [[ -f "$install_file" ]] || return 0
    sha256sum "$install_file" | awk '{print $1}' > "$MOD_HASH_FILE"
}

ensure_directories() {
    mkdir -p "$MODS_DIR" "$WORLDS_DIR" "$LOGS_DIR"
}

ensure_tmodloader_installed() {
    # The Docker build runs `install-tml --github` but it can fail silently
    # (unzip failure, version detection returning empty, etc.), leaving
    # $HOME/server without the actual tModLoader binary. Detect that here and
    # re-run install-tml so the server can actually start.
    local home_dir="${HOME:-/home/tml}"
    local script_caller="$home_dir/server/LaunchUtils/ScriptCaller.sh"
    local ver_marker="$home_dir/server/.ver"

    if [[ -f "$script_caller" ]]; then
        echo "[entrypoint] tModLoader binary present at $script_caller"
        mkdir -p "$home_dir/server/tModLoader-Logs"
        return 0
    fi

    echo "[entrypoint] tModLoader binary missing at $script_caller; running install-tml..."

    # Clear any stale version marker from a previous broken install — if .ver
    # exists and matches the new (also broken) version, install-tml skips the
    # actual install and returns "up to date" without doing anything.
    rm -f "$ver_marker"

    if ! ( cd "$home_dir" && ./manage-tModLoaderServer.sh install-tml --github ); then
        echo "[entrypoint] FATAL: install-tml exited with error" >&2
        exit 1
    fi

    # Verify the install actually produced the binary. install-tml can return 0
    # even when its internal unzip or version detection failed.
    if [[ ! -f "$script_caller" ]]; then
        echo "[entrypoint] FATAL: install-tml completed but $script_caller still missing" >&2
        echo "[entrypoint] contents of $home_dir/server:" >&2
        ls -la "$home_dir/server" >&2 || true
        exit 1
    fi

    # The manage script writes to $HOME/server/tModLoader-Logs/server.log before
    # cd'ing, so the directory must exist or the redirect fails.
    mkdir -p "$home_dir/server/tModLoader-Logs"
    echo "[entrypoint] install-tml complete"
}

seed_world_from_preload() {
    # Extract preload/Map/Terraria.zip into $WORLDS_DIR on first start so users
    # can ship a starter world with the deployment. NEVER overwrites: if any
    # .wld is already present in the volume, leave it alone.
    #
    # Supports two zip layouts:
    #   1. Direct .wld (and matching .twld) files at any depth in the zip.
    #   2. A tModLoader save-folder dump where the actual world only exists
    #      inside dated cloud-backup zips at tModLoader/Worlds/Backups/*.zip.
    #      In that case the newest backup is extracted and used.
    #
    # If the seeded world name differs from WORLD_NAME (e.g. backup was named
    # "Inferior_Touch_of_Power" but WORLD_NAME=untitled), updates WORLD_NAME in
    # this shell so determine_world_clause loads the seeded world.
    if find "$WORLDS_DIR" -maxdepth 1 -name "*.wld" -print -quit 2>/dev/null | grep -q .; then
        echo "[entrypoint] world already present in $WORLDS_DIR; preserving (no seed)"
        return 0
    fi

    local zip="${PRELOAD_DIR}/Map/Terraria.zip"
    if [[ ! -f "$zip" ]]; then
        echo "[entrypoint] no preload world zip at $zip; skipping world seed"
        return 0
    fi

    echo "[entrypoint] no existing world; seeding from $zip..."
    local tmp
    tmp=$(mktemp -d)
    # shellcheck disable=SC2064 — expand $tmp now, not at trap time
    trap "rm -rf '$tmp'" RETURN

    if ! unzip -q "$zip" -d "$tmp"; then
        echo "[entrypoint] WARNING: failed to extract $zip" >&2
        return 0
    fi

    # Strategy 1: direct .wld files (excluding *.bak* backups) anywhere in tree.
    local wld
    wld=$(find "$tmp" -name "*.wld" -not -name "*.bak*" -type f 2>/dev/null | head -1)

    # Strategy 2: extract the newest cloud-backup zip and look inside.
    if [[ -z "$wld" ]]; then
        local backup
        backup=$(find "$tmp" -name "*-cloud.zip" -type f 2>/dev/null | sort | tail -1)
        if [[ -n "$backup" ]]; then
            echo "[entrypoint] no direct .wld in outer zip; extracting backup $(basename "$backup")"
            mkdir -p "$tmp/_backup"
            unzip -q -o "$backup" -d "$tmp/_backup"
            wld=$(find "$tmp/_backup" -name "*.wld" -type f 2>/dev/null | head -1)
        fi
    fi

    if [[ -z "$wld" ]]; then
        echo "[entrypoint] WARNING: no .wld file found in $zip; not seeding" >&2
        return 0
    fi

    cp "$wld" "$WORLDS_DIR/"
    local twld="${wld%.wld}.twld"
    if [[ -f "$twld" ]]; then
        cp "$twld" "$WORLDS_DIR/"
    fi

    local seeded_name
    seeded_name=$(basename "$wld" .wld)
    echo "[entrypoint] seeded world '$seeded_name' into $WORLDS_DIR"

    if [[ "$seeded_name" != "$WORLD_NAME" ]]; then
        echo "[entrypoint] updating WORLD_NAME: '$WORLD_NAME' -> '$seeded_name' (matching seeded world)"
        WORLD_NAME="$seeded_name"
    fi
}

seed_mods_from_preload() {
    # Copy bundled mod files from the image's preload directory into the volume.
    # Only files that don't already exist at the target are copied — user-modified
    # files in the volume are preserved.
    local src="${PRELOAD_DIR}/Mods"
    if [[ ! -d "$src" ]]; then
        echo "[entrypoint] no preload at $src; skipping seed"
        return 0
    fi

    local copied=0 skipped=0
    shopt -s nullglob
    for file in "$src"/*; do
        local name
        name=$(basename "$file")
        local dest="$MODS_DIR/$name"
        if [[ -e "$dest" ]]; then
            skipped=$((skipped + 1))
        else
            cp "$file" "$dest"
            copied=$((copied + 1))
        fi
    done
    shopt -u nullglob
    echo "[entrypoint] preload seed: $copied copied, $skipped already present"
}

cleanup_legacy_workshop_routing() {
    # Earlier versions of this script tried two symlink schemes to route
    # SteamCMD's workshop output to the volume:
    #   1. /tModLoader/steamapps/workshop -> /home/tml/Steam/steamapps/workshop
    #      → stored content in ephemeral image layer; lost on redeploy
    #   2. /home/tml/Steam/steamapps -> /tModLoader/steamapps
    #      → caused "I/O Operation Failed" during SteamCMD downloads because
    #        atomic ops crossed mount boundaries (image layer ↔ Railway volume)
    # We now use straight copies (no symlinks). Remove any leftover symlinks
    # from those previous approaches.
    if [[ -L "/home/tml/Steam/steamapps" ]]; then
        local target
        target=$(readlink "/home/tml/Steam/steamapps")
        echo "[entrypoint] removing legacy forward symlink /home/tml/Steam/steamapps -> $target"
        rm "/home/tml/Steam/steamapps"
    fi
    if [[ -L "$TML_FOLDER/steamapps/workshop" ]]; then
        local target
        target=$(readlink "$TML_FOLDER/steamapps/workshop")
        echo "[entrypoint] removing legacy reverse symlink $TML_FOLDER/steamapps/workshop -> $target"
        rm "$TML_FOLDER/steamapps/workshop"
    fi
}

force_reinstall_if_hash_orphaned() {
    # A previous deploy may have written .install-hash even though the actual
    # workshop download failed (the manage script's install-mods returns 0
    # despite per-item "I/O Operation Failed" errors). If the hash is present
    # but the volume has no workshop content, mods_need_install would short-
    # circuit and the server would start with no workshop mods. Detect that
    # mismatch and clear the hash to force a clean re-install.
    [[ -f "$MOD_HASH_FILE" ]] || return 0
    local workshop_content="$TML_FOLDER/steamapps/workshop/content/1281930"
    if [[ ! -d "$workshop_content" ]] || [[ -z "$(ls -A "$workshop_content" 2>/dev/null)" ]]; then
        echo "[entrypoint] mod hash present but volume workshop content missing; forcing re-install"
        rm "$MOD_HASH_FILE"
    fi
}

restore_workshop_from_volume() {
    # SteamCMD checks its install dir (/home/tml/Steam/steamapps/workshop) for
    # currently-installed item versions before deciding what to download.
    # After a redeploy the image layer is fresh, so without this step SteamCMD
    # thinks nothing is installed and re-downloads every mod. Copying the
    # volume's content back into SteamCMD's view makes its version check pass
    # and reduces redeploys to a quick verify rather than ~350MB of downloads.
    local src="$TML_FOLDER/steamapps/workshop"
    local dest="/home/tml/Steam/steamapps/workshop"
    if [[ ! -d "$src" ]] || [[ -z "$(ls -A "$src" 2>/dev/null)" ]]; then
        echo "[entrypoint] no cached workshop content in volume; skipping restore"
        return 0
    fi
    mkdir -p "$dest"
    echo "[entrypoint] restoring workshop cache from volume to $dest..."
    # -r recursive, -n no-clobber. busybox cp supports both flags.
    cp -rn "$src/." "$dest/" 2>/dev/null || true
    echo "[entrypoint] workshop cache restored ($(du -sh "$dest" 2>/dev/null | cut -f1))"
}

sync_workshop_to_volume() {
    # Copy freshly-downloaded workshop content from SteamCMD's install dir
    # into the volume so (a) tModLoader (reading from $folder/steamapps/workshop
    # via -steamworkshopfolder) finds it on this start, and (b) it survives
    # the next container rebuild.
    local src="/home/tml/Steam/steamapps/workshop"
    local dest="$TML_FOLDER/steamapps/workshop"
    if [[ ! -d "$src" ]] || [[ -z "$(ls -A "$src" 2>/dev/null)" ]]; then
        echo "[entrypoint] no workshop content at $src to sync"
        return 0
    fi
    mkdir -p "$dest"
    echo "[entrypoint] syncing workshop content $src -> $dest..."
    # -r recursive. Overwrite is intentional here: we want the freshest
    # versions of any updated mods to make it into the volume.
    cp -r "$src/." "$dest/"
    echo "[entrypoint] workshop in volume: $(du -sh "$dest" 2>/dev/null | cut -f1)"
}

install_workshop_mods_directly() {
    # We invoke SteamCMD ourselves instead of going through the manage script's
    # install-mods command. The manage script does `pushd Mods` (= cwd in the
    # Railway volume) before running SteamCMD with `+force_install_dir $folder`,
    # which causes SteamCMD's internal atomic-rename ops to cross the image-
    # layer / volume filesystem boundary and fail with "I/O Operation Failed"
    # on every workshop item. Running SteamCMD with cwd in /home/tml keeps
    # all its operations on a single filesystem.
    local install_file="${MODS_DIR}/install.txt"
    [[ -f "$install_file" ]] || { echo "[entrypoint] no install.txt; nothing to install"; return 0; }

    # Parse workshop IDs (one per line, ignore blanks and comments)
    local ids=()
    local line
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%$'\r'}"            # strip CR (in case file has CRLF)
        line="${line//[[:space:]]/}"    # strip all whitespace
        [[ -z "$line" || "$line" == \#* ]] && continue
        ids+=("$line")
    done < "$install_file"

    if [[ ${#ids[@]} -eq 0 ]]; then
        echo "[entrypoint] install.txt has no workshop IDs"
        return 0
    fi

    echo "[entrypoint] downloading ${#ids[@]} workshop item(s) via direct SteamCMD..."

    # Pre-create SteamCMD's expected dirs so it doesn't fail on missing parents.
    mkdir -p /home/tml/Steam/steamapps/workshop/content
    mkdir -p /home/tml/Steam/steamapps/workshop/downloads

    # force_install_dir must NOT point at SteamCMD's own install folder —
    # SteamCMD refuses with "Please set the game install path to something
    # other than the Steam install folder" and aborts every download. Workshop
    # downloads ignore this dir anyway (they always go to
    # $STEAMCMD_HOME/steamapps/workshop), so any other path works. Keep it in
    # /home/tml so it stays on the image filesystem.
    local install_dir="/home/tml/.steamcmd-install-target"
    mkdir -p "$install_dir"

    local args=("+force_install_dir" "$install_dir" "+login" "anonymous")
    local id
    for id in "${ids[@]}"; do
        args+=("+workshop_download_item" "1281930" "$id")
    done
    args+=("+quit")

    local rc=0
    ( cd /home/tml && /home/tml/.bin/steamcmd "${args[@]}" ) || rc=$?

    if [[ $rc -ne 0 ]]; then
        echo "[entrypoint] SteamCMD exited with code $rc" >&2
        if [[ -f /home/tml/Steam/logs/stderr.txt ]]; then
            echo "[entrypoint] last lines of /home/tml/Steam/logs/stderr.txt:" >&2
            tail -30 /home/tml/Steam/logs/stderr.txt >&2 || true
        fi
        return 1
    fi
    return 0
}

install_mods_if_needed() {
    if mods_need_install; then
        echo "[entrypoint] install.txt changed - downloading workshop mods..."
        if install_workshop_mods_directly; then
            record_mod_hash
            echo "[entrypoint] mod install complete"
        else
            echo "[entrypoint] WARNING: mod install failed; starting server anyway" >&2
        fi
    else
        echo "[entrypoint] mods up to date; skipping install"
    fi
}

main() {
    echo "[entrypoint] preparing tModLoader server in $TML_FOLDER"
    ensure_directories
    ensure_tmodloader_installed
    seed_world_from_preload
    seed_mods_from_preload

    # Workshop content lives in two places and we copy between them:
    #   /home/tml/Steam/steamapps/workshop  ← SteamCMD writes here (ephemeral)
    #   $TML_FOLDER/steamapps/workshop      ← tModLoader reads here (persistent)
    cleanup_legacy_workshop_routing
    force_reinstall_if_hash_orphaned
    restore_workshop_from_volume

    local world_clause
    world_clause=$(determine_world_clause)
    echo "[entrypoint] world clause: $world_clause"

    generate_serverconfig "$world_clause" > "$SERVERCONFIG"
    echo "[entrypoint] wrote $SERVERCONFIG"

    install_mods_if_needed
    sync_workshop_to_volume

    # Bypass the manage script's `start` command. Its is_in_docker branch would
    # re-invoke install_workshop_mods with the broken cross-filesystem cwd, AND
    # try to redirect to a non-existent log file. Run ScriptCaller.sh directly
    # — that's what the manage script ultimately exec's anyway.
    local server_dir="$HOME/server"
    cd "$server_dir" || { echo "[entrypoint] FATAL: $server_dir missing" >&2; exit 1; }

    # The manage script applies these two tweaks to ScriptCaller.sh before
    # sourcing it; replicate them here.
    sed -i 's|cd "$(dirname "$0")"|cd "$(dirname "${BASH_SOURCE[0]}")"|' ./LaunchUtils/ScriptCaller.sh
    chmod +x ./LaunchUtils/ScriptCaller.sh

    echo "[entrypoint] starting tModLoader server"
    exec ./LaunchUtils/ScriptCaller.sh -server \
        -config "$SERVERCONFIG" \
        -steamworkshopfolder "$TML_FOLDER/steamapps/workshop" \
        -tmlsavedirectory "$TML_FOLDER"
}

# Skip main() when sourced for testing.
if [[ "${TML_WRAPPER_TEST_MODE:-0}" == "1" ]]; then
    set +e
    return 0 2>/dev/null || true
fi

main "$@"
