#!/bin/bash
# tModLoader server entrypoint wrapper.
# Generates serverconfig.txt from environment variables, detects existing worlds,
# performs hash-based mod installation, then execs the official management script.

set -euo pipefail

# Empty TMLVERSION trips up the manage script's get_version (it treats "" as a
# valid version string), making install-tml think the install is up to date
# even when it's broken. Treat empty == unset throughout.
if [[ -v TMLVERSION ]] && [[ -z "${TMLVERSION:-}" ]]; then
    unset TMLVERSION
fi

TML_FOLDER="${TML_FOLDER:-/tModLoader}"
MODS_DIR="${TML_FOLDER}/Mods"
WORLDS_DIR="${TML_FOLDER}/Worlds"
LOGS_DIR="${TML_FOLDER}/logs"
SERVERCONFIG="${TML_FOLDER}/serverconfig.txt"
MOD_HASH_FILE="${MODS_DIR}/.install-hash"
PRELOAD_DIR="${PRELOAD_DIR:-/preload}"

generate_serverconfig() {
    # Emit a serverconfig.txt body to stdout.
    # Arg 1: the world clause - either "world=<path>" or "autocreate=<size>".
    local world_clause="$1"

    cat <<EOF
# Auto-generated by entrypoint-wrapper.sh - edit .env on the host instead.
# Manual edits to this file will be overwritten on container restart.
worldpath=${WORLDS_DIR}
worldname=${WORLD_NAME}
${world_clause}
difficulty=${WORLD_DIFFICULTY}
maxplayers=${MAX_PLAYERS}
port=${SERVER_PORT}
password=${SERVER_PASSWORD}
motd=${MOTD}
secure=${SECURE}
language=${LANGUAGE}
autosave=${AUTOSAVE}
modpath=${MODS_DIR}
priority=1
EOF

    if [[ -n "${WORLD_SEED}" ]]; then
        echo "seed=${WORLD_SEED}"
    fi
}

determine_world_clause() {
    # Emit the world-related config lines.
    # Terraria's `autocreate` only works in conjunction with `-world`/`world=`,
    # which tells it where to create the file. Without `world=`, the server
    # ignores `autocreate` and drops into the interactive "Choose World:" prompt.
    # We always emit `world=<path>`, and add `autocreate=<size>` when the file
    # is missing so the server creates it at the same path.
    local target="${WORLDS_DIR}/${WORLD_NAME}.wld"
    echo "world=${target}"
    if [[ ! -f "$target" ]]; then
        echo "autocreate=${WORLD_SIZE}"
    fi
}

mods_need_install() {
    # Return 0 (success/true) if install.txt exists and differs from stored hash.
    # Return 1 (failure/false) if install.txt is missing or hash matches.
    local install_file="${MODS_DIR}/install.txt"
    [[ -f "$install_file" ]] || return 1

    local current_hash
    current_hash=$(sha256sum "$install_file" | awk '{print $1}')

    if [[ -f "$MOD_HASH_FILE" ]]; then
        local stored_hash
        stored_hash=$(cat "$MOD_HASH_FILE")
        [[ "$current_hash" != "$stored_hash" ]]
    else
        return 0
    fi
}

record_mod_hash() {
    # Write the current install.txt hash to MOD_HASH_FILE.
    local install_file="${MODS_DIR}/install.txt"
    [[ -f "$install_file" ]] || return 0
    sha256sum "$install_file" | awk '{print $1}' > "$MOD_HASH_FILE"
}

ensure_directories() {
    mkdir -p "$MODS_DIR" "$WORLDS_DIR" "$LOGS_DIR"
}

ensure_tmodloader_installed() {
    # The Docker build runs `install-tml --github` but it can fail silently
    # (unzip failure, version detection returning empty, etc.), leaving
    # $HOME/server without the actual tModLoader binary. Detect that here and
    # re-run install-tml so the server can actually start.
    local home_dir="${HOME:-/home/tml}"
    local script_caller="$home_dir/server/LaunchUtils/ScriptCaller.sh"
    local ver_marker="$home_dir/server/.ver"

    if [[ -f "$script_caller" ]]; then
        echo "[entrypoint] tModLoader binary present at $script_caller"
        mkdir -p "$home_dir/server/tModLoader-Logs"
        return 0
    fi

    echo "[entrypoint] tModLoader binary missing at $script_caller; running install-tml..."

    # Clear any stale version marker from a previous broken install — if .ver
    # exists and matches the new (also broken) version, install-tml skips the
    # actual install and returns "up to date" without doing anything.
    rm -f "$ver_marker"

    if ! ( cd "$home_dir" && ./manage-tModLoaderServer.sh install-tml --github ); then
        echo "[entrypoint] FATAL: install-tml exited with error" >&2
        exit 1
    fi

    # Verify the install actually produced the binary. install-tml can return 0
    # even when its internal unzip or version detection failed.
    if [[ ! -f "$script_caller" ]]; then
        echo "[entrypoint] FATAL: install-tml completed but $script_caller still missing" >&2
        echo "[entrypoint] contents of $home_dir/server:" >&2
        ls -la "$home_dir/server" >&2 || true
        exit 1
    fi

    # The manage script writes to $HOME/server/tModLoader-Logs/server.log before
    # cd'ing, so the directory must exist or the redirect fails.
    mkdir -p "$home_dir/server/tModLoader-Logs"
    echo "[entrypoint] install-tml complete"
}

seed_mods_from_preload() {
    # Copy bundled mod files from the image's preload directory into the volume.
    # Only files that don't already exist at the target are copied — user-modified
    # files in the volume are preserved.
    local src="${PRELOAD_DIR}/Mods"
    if [[ ! -d "$src" ]]; then
        echo "[entrypoint] no preload at $src; skipping seed"
        return 0
    fi

    local copied=0 skipped=0
    shopt -s nullglob
    for file in "$src"/*; do
        local name
        name=$(basename "$file")
        local dest="$MODS_DIR/$name"
        if [[ -e "$dest" ]]; then
            skipped=$((skipped + 1))
        else
            cp "$file" "$dest"
            copied=$((copied + 1))
        fi
    done
    shopt -u nullglob
    echo "[entrypoint] preload seed: $copied copied, $skipped already present"
}

link_steamcmd_workshop_to_volume() {
    # SteamCMD's workshop_download_item ignores `+force_install_dir` and writes
    # to its own home ($HOME/Steam/steamapps/workshop). The manage script's
    # start command passes `-steamworkshopfolder $folder/steamapps/workshop` to
    # tModLoader, which looks for downloaded mods there. Bridge the two paths
    # with a symlink so tModLoader actually finds the workshop content.
    local home_dir="${HOME:-/home/tml}"
    local src="$home_dir/Steam/steamapps/workshop"
    local dest="$TML_FOLDER/steamapps/workshop"

    if [[ ! -d "$src" ]]; then
        echo "[entrypoint] no SteamCMD workshop dir at $src; skipping symlink"
        return 0
    fi

    mkdir -p "$TML_FOLDER/steamapps"

    if [[ -L "$dest" ]]; then
        if [[ "$(readlink "$dest")" == "$src" ]]; then
            echo "[entrypoint] workshop symlink already correct: $dest -> $src"
            return 0
        fi
        rm "$dest"
    elif [[ -e "$dest" ]]; then
        # Real directory at the destination (shouldn't normally happen) — bail
        # rather than risk deleting user data.
        echo "[entrypoint] WARNING: $dest exists as a regular path, not a symlink. Skipping." >&2
        return 0
    fi

    ln -s "$src" "$dest"
    echo "[entrypoint] linked $dest -> $src"
}

install_mods_if_needed() {
    if mods_need_install; then
        echo "[entrypoint] install.txt changed - downloading workshop mods..."
        if "$HOME/manage-tModLoaderServer.sh" install-mods --folder "$TML_FOLDER"; then
            record_mod_hash
            echo "[entrypoint] mod install complete"
        else
            echo "[entrypoint] WARNING: mod install failed; starting server anyway" >&2
        fi
    else
        echo "[entrypoint] mods up to date; skipping install"
    fi
}

main() {
    echo "[entrypoint] preparing tModLoader server in $TML_FOLDER"
    ensure_directories
    ensure_tmodloader_installed
    seed_mods_from_preload

    local world_clause
    world_clause=$(determine_world_clause)
    echo "[entrypoint] world clause: $world_clause"

    generate_serverconfig "$world_clause" > "$SERVERCONFIG"
    echo "[entrypoint] wrote $SERVERCONFIG"

    install_mods_if_needed
    link_steamcmd_workshop_to_volume

    echo "[entrypoint] starting tModLoader server"
    # NOTE: not passing --config — the manage script always loads
    # $folder/serverconfig.txt which is exactly the file we just wrote, so an
    # extra --config flag just leaks into the tModLoader CLI as $start_args
    # where the double-dash form is unrecognized.
    exec "$HOME/manage-tModLoaderServer.sh" start --folder "$TML_FOLDER"
}

# Skip main() when sourced for testing.
if [[ "${TML_WRAPPER_TEST_MODE:-0}" == "1" ]]; then
    set +e
    return 0 2>/dev/null || true
fi

main "$@"
