#!/bin/bash
# tModLoader server entrypoint wrapper.
#
# - Generates serverconfig.txt from environment variables on each start.
# - Seeds an initial world from preload/Map/Terraria.zip on first run.
# - Syncs mods against /preload/mods.json (single source of truth):
#     downloads missing/changed .tmod files from GitHub Releases,
#     verifies sha256, and rewrites enabled.json from the manifest.
# - Verifies the tModLoader binary is present; reinstalls if not.
# - Execs the tModLoader server directly.

set -euo pipefail

# Empty TMLVERSION trips up the manage script's get_version (it treats "" as a
# valid version string), making install-tml think the install is up to date
# even when it's broken. Treat empty == unset throughout.
if [[ -v TMLVERSION ]] && [[ -z "${TMLVERSION:-}" ]]; then
    unset TMLVERSION
fi

TML_FOLDER="${TML_FOLDER:-/tModLoader}"
MODS_DIR="${TML_FOLDER}/Mods"
WORLDS_DIR="${TML_FOLDER}/Worlds"
LOGS_DIR="${TML_FOLDER}/logs"
SERVERCONFIG="${TML_FOLDER}/serverconfig.txt"
PRELOAD_DIR="${PRELOAD_DIR:-/preload}"

generate_serverconfig() {
    # Emit a serverconfig.txt body to stdout.
    # Arg 1: the world clause - either "world=<path>" or "autocreate=<size>".
    local world_clause="$1"

    cat <<EOF
# Auto-generated by entrypoint-wrapper.sh - edit .env on the host instead.
# Manual edits to this file will be overwritten on container restart.
worldpath=${WORLDS_DIR}
worldname=${WORLD_NAME}
${world_clause}
difficulty=${WORLD_DIFFICULTY}
maxplayers=${MAX_PLAYERS}
port=${SERVER_PORT}
password=${SERVER_PASSWORD}
motd=${MOTD}
secure=${SECURE}
language=${LANGUAGE}
autosave=${AUTOSAVE}
modpath=${MODS_DIR}
priority=1
EOF

    if [[ -n "${WORLD_SEED}" ]]; then
        echo "seed=${WORLD_SEED}"
    fi
}

determine_world_clause() {
    # Emit the world-related config lines.
    # Terraria's `autocreate` only works in conjunction with `-world`/`world=`,
    # which tells it where to create the file. Without `world=`, the server
    # ignores `autocreate` and drops into the interactive "Choose World:" prompt.
    # We always emit `world=<path>`, and add `autocreate=<size>` when the file
    # is missing so the server creates it at the same path.
    local target="${WORLDS_DIR}/${WORLD_NAME}.wld"
    echo "world=${target}"
    if [[ ! -f "$target" ]]; then
        echo "autocreate=${WORLD_SIZE}"
    fi
}

ensure_directories() {
    mkdir -p "$MODS_DIR" "$WORLDS_DIR" "$LOGS_DIR"
}

ensure_tmodloader_installed() {
    # The Docker build runs `install-tml --github` but it can fail silently
    # (unzip failure, version detection returning empty, etc.), leaving
    # $HOME/server without the actual tModLoader binary. Detect that here and
    # re-run install-tml so the server can actually start.
    local home_dir="${HOME:-/home/tml}"
    local script_caller="$home_dir/server/LaunchUtils/ScriptCaller.sh"
    local ver_marker="$home_dir/server/.ver"

    if [[ -f "$script_caller" ]]; then
        echo "[entrypoint] tModLoader binary present at $script_caller"
        mkdir -p "$home_dir/server/tModLoader-Logs"
        return 0
    fi

    echo "[entrypoint] tModLoader binary missing at $script_caller; running install-tml..."

    # Clear any stale version marker from a previous broken install — if .ver
    # exists and matches the new (also broken) version, install-tml skips the
    # actual install and returns "up to date" without doing anything.
    rm -f "$ver_marker"

    if ! ( cd "$home_dir" && ./manage-tModLoaderServer.sh install-tml --github ); then
        echo "[entrypoint] FATAL: install-tml exited with error" >&2
        exit 1
    fi

    if [[ ! -f "$script_caller" ]]; then
        echo "[entrypoint] FATAL: install-tml completed but $script_caller still missing" >&2
        echo "[entrypoint] contents of $home_dir/server:" >&2
        ls -la "$home_dir/server" >&2 || true
        exit 1
    fi

    mkdir -p "$home_dir/server/tModLoader-Logs"
    echo "[entrypoint] install-tml complete"
}

seed_world_from_preload() {
    # Extract preload/Map/Terraria.zip into $WORLDS_DIR on first start so users
    # can ship a starter world with the deployment. NEVER overwrites: if any
    # .wld is already present in the volume, leave it alone.
    #
    # Supports two zip layouts:
    #   1. Direct .wld (and matching .twld) files at any depth in the zip.
    #   2. A tModLoader save-folder dump where the actual world only exists
    #      inside dated cloud-backup zips at tModLoader/Worlds/Backups/*.zip.
    #      In that case the newest backup is extracted and used.
    #
    # If the seeded world name differs from WORLD_NAME, updates WORLD_NAME in
    # this shell so determine_world_clause loads the seeded world.
    if find "$WORLDS_DIR" -maxdepth 1 -name "*.wld" -print -quit 2>/dev/null | grep -q .; then
        echo "[entrypoint] world already present in $WORLDS_DIR; preserving (no seed)"
        return 0
    fi

    local zip="${PRELOAD_DIR}/Map/Terraria.zip"
    if [[ ! -f "$zip" ]]; then
        echo "[entrypoint] no preload world zip at $zip; skipping world seed"
        return 0
    fi

    echo "[entrypoint] no existing world; seeding from $zip..."
    local tmp
    tmp=$(mktemp -d)
    # shellcheck disable=SC2064 — expand $tmp now, not at trap time
    trap "rm -rf '$tmp'" RETURN

    if ! unzip -q "$zip" -d "$tmp"; then
        echo "[entrypoint] WARNING: failed to extract $zip" >&2
        return 0
    fi

    # Strategy 1: direct .wld files (excluding *.bak* backups) anywhere in tree.
    local wld
    wld=$(find "$tmp" -name "*.wld" -not -name "*.bak*" -type f 2>/dev/null | head -1)

    # Strategy 2: extract the newest cloud-backup zip and look inside.
    if [[ -z "$wld" ]]; then
        local backup
        backup=$(find "$tmp" -name "*-cloud.zip" -type f 2>/dev/null | sort | tail -1)
        if [[ -n "$backup" ]]; then
            echo "[entrypoint] no direct .wld in outer zip; extracting backup $(basename "$backup")"
            mkdir -p "$tmp/_backup"
            unzip -q -o "$backup" -d "$tmp/_backup"
            wld=$(find "$tmp/_backup" -name "*.wld" -type f 2>/dev/null | head -1)
        fi
    fi

    if [[ -z "$wld" ]]; then
        echo "[entrypoint] WARNING: no .wld file found in $zip; not seeding" >&2
        return 0
    fi

    cp "$wld" "$WORLDS_DIR/"
    local twld="${wld%.wld}.twld"
    if [[ -f "$twld" ]]; then
        cp "$twld" "$WORLDS_DIR/"
    fi

    local seeded_name
    seeded_name=$(basename "$wld" .wld)
    echo "[entrypoint] seeded world '$seeded_name' into $WORLDS_DIR"

    if [[ "$seeded_name" != "$WORLD_NAME" ]]; then
        echo "[entrypoint] updating WORLD_NAME: '$WORLD_NAME' -> '$seeded_name' (matching seeded world)"
        WORLD_NAME="$seeded_name"
    fi
}

sync_mods_from_manifest() {
    # Reconcile $MODS_DIR with /preload/mods.json on every start.
    #
    # The manifest is the single source of truth: each entry has {name, sha256}.
    # The URL is derived as <release_base_url>/<name>.tmod. For each mod, the
    # existing file is kept iff its sha256 matches; otherwise it is downloaded
    # to a .partial path and atomically renamed only after verification.
    #
    # Idempotent: re-runs are cheap (sha256 check, no network if all match).
    local manifest="${PRELOAD_DIR}/mods.json"
    if [[ ! -f "$manifest" ]]; then
        echo "[entrypoint] FATAL: $manifest missing — image is broken" >&2
        exit 1
    fi

    local base_url count
    base_url=$(jq -r '.release_base_url' "$manifest")
    count=$(jq -r '.mods | length' "$manifest")
    if [[ -z "$base_url" || "$base_url" == "null" ]]; then
        echo "[entrypoint] FATAL: mods.json missing release_base_url" >&2
        exit 1
    fi

    echo "[entrypoint] syncing $count mods from $base_url"

    local i name expected_sha actual_sha dest url tmp
    for ((i = 0; i < count; i++)); do
        name=$(jq -r ".mods[$i].name" "$manifest")
        expected_sha=$(jq -r ".mods[$i].sha256" "$manifest")
        # Validate trusted-but-still-checked manifest fields: a missing/null
        # value would silently corrupt downloads; a name with slashes or ".."
        # would let the URL path escape MODS_DIR.
        if [[ -z "$name" || "$name" == "null" || -z "$expected_sha" || "$expected_sha" == "null" ]]; then
            echo "[entrypoint] FATAL: mods[$i] missing name or sha256 in $manifest" >&2
            exit 1
        fi
        if [[ "$name" == */* || "$name" == *..* ]]; then
            echo "[entrypoint] FATAL: invalid mod name in manifest: '$name'" >&2
            exit 1
        fi
        dest="${MODS_DIR}/${name}.tmod"
        url="${base_url}/${name}.tmod"

        if [[ -f "$dest" ]]; then
            actual_sha=$(sha256sum "$dest" | cut -d' ' -f1)
            if [[ "$actual_sha" == "$expected_sha" ]]; then
                echo "[entrypoint]   ${name}: up to date"
                continue
            fi
            echo "[entrypoint]   ${name}: sha256 mismatch; redownloading"
        else
            echo "[entrypoint]   ${name}: missing; downloading"
        fi

        tmp="${dest}.partial"
        if ! curl -fL --retry 3 --retry-delay 5 -o "$tmp" "$url"; then
            echo "[entrypoint] FATAL: download failed for ${name} from ${url}" >&2
            rm -f "$tmp"
            exit 1
        fi
        actual_sha=$(sha256sum "$tmp" | cut -d' ' -f1)
        if [[ "$actual_sha" != "$expected_sha" ]]; then
            echo "[entrypoint] FATAL: ${name} sha256 mismatch after download" >&2
            echo "[entrypoint]   expected: $expected_sha" >&2
            echo "[entrypoint]   actual:   $actual_sha" >&2
            rm -f "$tmp"
            exit 1
        fi
        mv "$tmp" "$dest"
    done
}

write_enabled_json() {
    # enabled.json is derived from the manifest and always rewritten on start.
    # tModLoader sometimes regenerates this file with an empty list during
    # server bootstrap; overwriting it post-sync guarantees the server loads
    # the exact mod set in the manifest, with no stale-volume failure modes.
    local manifest="${PRELOAD_DIR}/mods.json"
    local target="${MODS_DIR}/enabled.json"
    jq '[.mods[].name]' "$manifest" > "$target"
    echo "[entrypoint] wrote $target ($(jq length "$target") mods enabled)"
}

main() {
    echo "[entrypoint] preparing tModLoader server in $TML_FOLDER"
    ensure_directories
    ensure_tmodloader_installed
    seed_world_from_preload
    sync_mods_from_manifest
    write_enabled_json

    local world_clause
    world_clause=$(determine_world_clause)
    echo "[entrypoint] world clause: $world_clause"

    generate_serverconfig "$world_clause" > "$SERVERCONFIG"
    echo "[entrypoint] wrote $SERVERCONFIG"

    # Bypass the manage script's `start` command — its is_in_docker branch
    # would re-invoke SteamCMD on every launch (which fails in this env),
    # and also tries to redirect output to a log file that may not exist.
    # Launch tModLoader directly via the same ScriptCaller.sh that manage
    # ultimately exec's.
    local server_dir="$HOME/server"
    cd "$server_dir" || { echo "[entrypoint] FATAL: $server_dir missing" >&2; exit 1; }

    # The manage script applies these two tweaks to ScriptCaller.sh before
    # sourcing it; replicate them here.
    sed -i 's|cd "$(dirname "$0")"|cd "$(dirname "${BASH_SOURCE[0]}")"|' ./LaunchUtils/ScriptCaller.sh
    chmod +x ./LaunchUtils/ScriptCaller.sh

    echo "[entrypoint] starting tModLoader server"
    exec ./LaunchUtils/ScriptCaller.sh -server \
        -config "$SERVERCONFIG" \
        -tmlsavedirectory "$TML_FOLDER"
}

# Skip main() when sourced for testing.
if [[ "${TML_WRAPPER_TEST_MODE:-0}" == "1" ]]; then
    set +e
    return 0 2>/dev/null || true
fi

main "$@"
